### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by aalborz** [redcanaryco/cb-response-surveyor#5]
I'm getting an error when trying to install Surveyor. After I run the command "python setup.py develop" I get the following:

build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by brianebeyer** [comment]
What operating system are you running?

If Ubuntu, you may need to `sudo apt-get install libssl-dev`

If CentOS/RHEL, you may need to `sudo yum install openssl-devel`

**Comment by aalborz** [comment]
Thanks that worked. But when I tried to install cbapi I got this:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 59, in <module>
    vendored('urllib3.contrib.pyopenssl')
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 32, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by brianebeyer** [comment]
What operating system are you running?

**Comment by brianebeyer** [comment]
Regardless, the internet seems to think you should upgrade pyopenssl:
```
$ sudo pip install -U pyopenssl
```

**Comment by keithmccammon** [comment]
@aalborz Is this resolved? This seems to be a problem with your local environment and not with the tool itself.

**Comment by mackwage** [comment]
Had this same issue. Can confirm @brianebeyer's suggestion to upgrade pyopenssl fixed

**Comment by keithmccammon** [comment]
Fantastic, thank you!
